---
name: Lumen Toolchain
description: |
  Installs the Lumen toolchain with Mise, ensuring caching works properly.
runs:
  using: composite
  steps:
    - name: Setup Rust caching
      uses: Swatinem/rust-cache@v2
      with:
        cache-directories: |
          /home/runner/.rustup
          /home/runner/.cargo/binstall
          /home/runner/.cargo/env
        cache-bin: 'true'

    - name: Setup mise
      uses: jdx/mise-action@v4
      with:
        install: true
        cache: true
