#
# Configuration for GitHub-based CI, based on the stock GitHub Rust config.
#
---
name: Rust

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request: {}

jobs:
  check-style:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up toolchain
        uses: ./.github/actions/toolchain

      - name: Report cargo version
        run: cargo --version
      - name: Report rustfmt version
        run: cargo fmt -- --version
      - name: Check style
        run: cargo fmt -- --check

  clippy-lint:
    runs-on: ubuntu-22.04
    env:
      CARGO_INCREMENTAL: 0
    steps:
      - name: Set up toolchain
        uses: ./.github/actions/toolchain

      - name: Report cargo version
        run: cargo --version
      - name: Report clippy version
        run: cargo clippy -- --version
      - name: Run clippy lints
        run: cargo xtask clippy

  test:
    runs-on: ubuntu-22.04
    env:
      CARGO_INCREMENTAL: 0
    steps:
      - name: Set up toolchain
        uses: ./.github/actions/toolchain

      - name: Report cargo version
        run: cargo --version
      - name: Report Nextest version
        run: cargo nextest --version
      - name: Run clippy lints
        run: cargo nextest run --workspace --all-features
